version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      - lint
      - build
jobs:
  lint:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run clean
      - run: npm run format
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run clean
      - run: npm run build